---
title: "Ссылки"
output: html_document
---

### R и R-Studio

[R] (http://www.r-project.org) — это бесплатный язык программирования с открытым исходным кодом, который можно использовать для статистического анализа, моделирования данных, построения диаграмм и многих других целей и задач. Еще одна бесплатная программа — [R-studio] (http://www.rstudio.com), предоставляющая удобный графический интерфейс для R. Сначала загрузите R, а затем загрузите R-studio. Оба могут работать на ПК, Mac или Linux. Учащиеся будут изучать R на лабораторных работах по статистике, используя это пособие[]().

### Дополнительные ресурсы R

1. Используйте Google, погуглите свою проблему
2. Используйте [Stackoverflow] (https://stackoverflow.com) , Google часто приводит Вас к нему, потому что кто-то уже задал ваш вопрос, и кто-то другой уже ответил, обычно многие люди отвечали на Ваш вопрос разными способами.
3. [Бесплатный учебник по психологической статистике с использованием R] (https://compcogscisydney.org/learning-statistics-with-r/), его стоит использовать (некоторые из этого пособия основаны на учебниках Даниэль)
4. Создан веб-сайт для ознакомления с R, он великолепен, оцените его (также создан с использованием R markdown): [http://compcogscisydney.org/psyr/](http://compcogscisydney.org/psyr /)
5. Ознакомьтесь с немного более старой книгой по программированию, в которой также представлен R [https://crumplab.github.io/programmingforpsych/](https://crumplab.github.io/programmingforpsych/)
6. Это исчерпывающее руководство по всем вопросам, связанным с R Markdown (вы обнаружите, что оно очень полезно, когда вы овладеете этим навыком): [https://bookdown.org/yihui/rmarkdown/](https://bookdown.org /yihui/rmarkdown/)

